services:
  qdrant:
    image: qdrant/qdrant:v1.19.1
    restart: "no"
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    volumes:
      - type: bind
        source: __QDRANT_DATA_DIR__
        target: /qdrant/storage
